[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

# Ana sayfa yönlendirmesi
[[redirects]]
  from = "/"
  to = "/tarpovizyon.html"
  status = 200

# Embed sayfası yönlendirmesi
[[redirects]]
  from = "/embed"
  to = "/embed.html"
  status = 200

# Mobil embed sayfası yönlendirmesi
[[redirects]]
  from = "/mobile-embed"
  to = "/mobile-embed.html"
  status = 200

# Widget sayfası yönlendirmesi
[[redirects]]
  from = "/widget"
  to = "/widget.html"
  status = 200

# İframe kılavuzu yönlendirmesi
[[redirects]]
  from = "/iframe-guide"
  to = "/iframe-guide.html"
  status = 200

# İframe yardım sayfası
[[redirects]]
  from = "/help"
  to = "/iframe-guide.html"
  status = 200

# Gemini API proxy route
[[redirects]]
  from = "/api/gemini/chat"
  to = "/.netlify/functions/gemini-proxy"
  status = 200

# Mistral API proxy route (eski versiyon için)
[[redirects]]
  from = "/api/mistral/chat"
  to = "/.netlify/functions/mistral-proxy"
  status = 200

# Basit API proxy route
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/gemini-proxy"
  status = 200

# TTS API proxy route
[[redirects]]
  from = "/api/tts"
  to = "/.netlify/functions/tts-proxy"
  status = 200

# 404 sayfası için yönlendirme
[[redirects]]
  from = "/*"
  to = "/tarpovizyon.html"
  status = 404

# Minimal güvenlik headers - iframe desteği için
# /tarpovizyon.html için header yok (iframe izni için)

# Embed sayfaları için header yok (iframe izni)
# /mobile-embed.html, /embed.html, /widget.html için header tanımlanmadı

# API fonksiyonları için CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Functions konfigürasyonu
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

# Environment variables için template
# Netlify Dashboard'da şunları ekleyin:
# GEMINI_API_KEY = your_gemini_api_key_here
# HUGGING_FACE_API_KEY = your_hugging_face_api_key_here
